-- Evolução MVP HelpZone Social Study Network
-- Execute no banco de produção com backup prévio.

ALTER TABLE post ADD COLUMN IF NOT EXISTS tipo_post VARCHAR(30) DEFAULT 'geral';
ALTER TABLE post ADD COLUMN IF NOT EXISTS materia VARCHAR(80);
ALTER TABLE post ADD COLUMN IF NOT EXISTS link_url VARCHAR(500);
ALTER TABLE post ADD COLUMN IF NOT EXISTS origem_automatica BOOLEAN DEFAULT FALSE;
ALTER TABLE post ADD COLUMN IF NOT EXISTS fixado_no_perfil BOOLEAN DEFAULT FALSE;
ALTER TABLE post ADD COLUMN IF NOT EXISTS editado BOOLEAN DEFAULT FALSE;

ALTER TABLE post_comentario ADD COLUMN IF NOT EXISTS parent_id INTEGER REFERENCES post_comentario(id);

ALTER TABLE perfil_social ADD COLUMN IF NOT EXISTS objetivo_estudo VARCHAR(200);
ALTER TABLE perfil_social ADD COLUMN IF NOT EXISTS prova_alvo VARCHAR(100);

ALTER TABLE story ADD COLUMN IF NOT EXISTS texto_curto VARCHAR(220);
ALTER TABLE story ADD COLUMN IF NOT EXISTS meta_dia VARCHAR(180);
ALTER TABLE story ADD COLUMN IF NOT EXISTS checkin_rapido BOOLEAN DEFAULT FALSE;
